title = "DropTea P2P"

[server]
host = '0.0.0.0'
port = 8081
buffer_size = 65536
timeout = 30
mode = "quic"
node_name = "NODE-B"

[storage]
save_path = './downloads_b'
temp_path = './temp_b'

[protocol]
header_format = "128sQ32s"
header_size = 168

# UUID Service : D7EA , Char. UUID : D7EB 
[dev]
enabled = true              # แสดงตัวเองหรือไม่ และ Bluetooth

#  เพิ่มหมวดนี้
[logging]
debug = false                # ค่า Default: false = เงียบ (Production), true = พูดมาก (Dev)
file_path = "logs/app.jsonl" # ที่เก็บไฟล์ Log